name: flutter_web_dashboard
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1
  get: ^4.6.6
  intl: 0.19.0
  syncfusion_flutter_charts: ^26.2.10

dev_dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/presentation/theme/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: ProjectAssets

  fonts:
    enabled: true
    outputs:
      class_name: ProjectFontFamily

  colors:
    enabled: false

  get: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: MyriadPro
      fonts:
        - asset: assets/fonts/MyriadPro/MyriadPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MyriadPro/MyriadPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyriadPro/MyriadPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MyriadPro/MyriadPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MyriadPro/MyriadPro-Light.ttf
          weight: 300
