name: learnsphere
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  change_app_package_name: ^1.3.0
  cloud_firestore: ^5.2.1
  email_validator: ^3.0.0
  file_picker: ^8.1.2
  firebase_admin: ^0.3.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.7.0
  flutter_platform_widgets: ^7.0.1
  flutter_svg: 2.0.10+1
  fluttertoast: ^8.2.8
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  oktoast: ^3.4.0
  otp_text_field: ^1.1.3
  story_view: ^0.16.5
  syncfusion_flutter_charts: ^26.2.10
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/presentation/theme/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: ProjectAssets

  fonts:
    enabled: true
    outputs:
      class_name: ProjectFontFamily

  colors:
    enabled: false

  get: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/icons/setting-2.svg

  fonts:
    - family: MyriadPro
      fonts:
        - asset: assets/fonts/MyriadPro/MyriadPro-Black.ttf
          weight: 900
        - asset: assets/fonts/MyriadPro/MyriadPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MyriadPro/MyriadPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MyriadPro/MyriadPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MyriadPro/MyriadPro-Light.ttf
          weight: 300
