name: sociogram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  calendar_date_picker2: ^0.5.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_share: ^2.0.0
  flutter_svg: 2.0.10+1
  get: any
  get_cli: ^1.8.1
  getwidget: ^3.1.1
  image_picker: ^1.0.0
  intl_phone_number_field: ^0.1.7
  otp_text_field: ^1.1.3
  smooth_page_indicator: ^1.1.0
  story_view: ^0.16.5
  syncfusion_flutter_charts: ^22.1.37
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Urbanist
      fonts:
        - asset: asset/Urbanist-Black.ttf
    - family: Urbanist-medium
      fonts:
        - asset: asset/Urbanist-Medium.ttf
    - family: Urbanist-semibold
      fonts:
        - asset: asset/Urbanist-SemiBold.ttf
    - family: Urbanist-bold
      fonts:
        - asset: asset/Urbanist-Bold.ttf
    - family: Urbanist-regular
      fonts:
        - asset: asset/Urbanist-Regular.ttf
